env:
  browser: true
  es6: true
  node: true
  webextensions: true
  jquery: true
globals:
  XRegExp: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2019
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console: ["warn", { allow: ["warn", "error"] }]
