# these are `libexec` specific eslint settings that override parts of the root eslintrc
parserOptions:
  sourceType: script
rules:
  # allow console since libexec scripts are only used in development and
  # console.logs are meaningful prompts to the devs
  no-console: 0